import Head from 'next/head';
import {motion} from 'framer-motion'
import Splash from '../components/splash/Splash.jsx';

export default function Home() {
  return (
    <motion.div
      exit = {{ opacity: 0 }}
      initial = {{ opacity: 0 }}
      animate = {{ opacity: 1 }}>
      <Head>
        <title>Gamut</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Splash/>
    </motion.div>
  )
}
